### PR TITLE
add json-tag

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by mattn** [comment]
I'm not sure the testdata is valid.

**Comment by tagomoris** [comment]
I'm not sure what this change is for. Is it to create readable configuration for tests?

**Comment by mattn** [comment]
> I'm not sure what this change is for. Is it to create readable configuration for tests?

not just for tests. I don't hope to write configuration in my code.

**Comment by tagomoris** [comment]
I got it.
Could you rebase it and add some options newly added? Others are ok for merge.

**Comment by mattn** [comment]
test failed but not json-config. it's Test_MarshalAsMsgpack. FYI, go's map is not ordered-map.

**Comment by tagomoris** [comment]
@mattn I rebuilt and confirmed to pass tests.
Off topic: do you have a good practice for such tests (order of maps) in go?

**Comment by mattn** [comment]
go doesn't have safety to compare map with reflect.DeepEquals. But json.Encode is safe to check because keys are encoded in the order. So you can do:

```go
b1, _ := json.Marshal(map1)
b2. _ := json.Marshal(map2)
if string(b1) != string(b2) {
  // do something
}
```

**Comment by tagomoris** [comment]
@mattn Thank you for great information!

**Comment by tagomoris** [comment]
Merged. Thank you for contribution.

**Pull request merged**
