### PR TITLE
Fix to change dependency from ugorji/go/codec to msgp code generation

### PR DESCRIPTION
**Pull request by tagomoris**
* ugorji/go/codec is very big library to include many codecs not only msgpack
* we need very simple marshaling only, for some specified structs
* this change is to decrease dependency problem
  * and this code runs faster than ugorji/go/codec (many benchmark says so)

### CODE REVIEW

**Comment by tagomoris** [comment]
@mattn Thank you for comment, but it's out of this patch's range. I'll fix it later...

**Comment by t-k** [comment]
Did not work, on my machine.
IMHO, you should use tuple directive.
https://github.com/tinylib/msgp/wiki/Preprocessor-Directives#tuple

Add ```//msgp:tuple Message``` to proto.go and tested again, it worked.

**Comment by tagomoris** [comment]
@t-k Thank you to point it out. I fixed and tested again in my environment.
Could you test once more?

**Comment by t-k** [comment]
@tagomoris Sorry for late reply.
Tested again and it worked. Thanks for the fix.

**Comment by tagomoris** [comment]
@t-k Thanks!

**Comment by tagomoris** [comment]
Merged. I'll tag this change as `v0.6.0`.

**Pull request merged**
