### PR TITLE
TLS Support

### PR DESCRIPTION
**Pull request by zonito**
Created another PR because of --signoff meshed up in https://github.com/fluent/fluent-logger-golang/pull/96

### CODE REVIEW

**Comment by zonito** [comment]
@tagomoris All commits are signed off.

**Comment by zonito** [comment]
@tagomoris - Can we merge this?

**Comment by tagomoris** [comment]
This change looks good to me. I want confirmation from other maintainers.
@fluent/golang-maintainers What do you think?

**Comment by fujimotos** [comment]
@tagomoris @zonito  FWIW, I'm start testing this patch tonight.
I'll post more update tomorrow, so wait for me.

**Comment by fujimotos** [comment]
I spent some time this evening testing this patch with Fluentd v1.14.2.
Attached below are the testing assets I crafted for the test.

_TLDR_ I could confirm that fluent-logger-golang now can connect to
Fluentd via TLS with @zonito's patch.
 
**fluentd.conf**

```xml
<source>
  @type forward
  <transport tls>
    cert_path fluentd.crt
    private_key_path fluentd.key
    private_key_passphrase *********
  </transport>
</source>

<match debug.**>
  @type stdout
</match>
```

**main.go**

```go
package main

import (
  "github.com/fluent/fluent-logger-golang/fluent"
)

func main() {
  logger, err := fluent.New(fluent.Config{FluentNetwork: "tls", TlsInsecureSkipVerify: true})
  if err != nil {
    return
  }
  defer logger.Close()
  var data = map[string]string{"foo":  "bar", "hoge": "hoge"}
  logger.Post("debug.log", data)
}
```

**Result**

```console
2021-11-19 20:42:19.000000000 +0900 debug.log: {"foo":"bar","hoge":"hoge"}
2021-11-19 20:42:34.000000000 +0900 debug.log: {"foo":"bar","hoge":"hoge"}
2021-11-19 20:42:34.000000000 +0900 debug.log: {"foo":"bar","hoge":"hoge"}
```

**Comment by zonito** [comment]
@tagomoris @fujimotos Let's merge this.. then

**Comment by fujimotos** [comment]
@tagomoris @zonito I'm basically okay with this patch, so I'll step ahead
and gonna merge this PR this weekend (probably on Sunday).

>  013a672 

it looks to me that @zonito accidentally overwrote c16ce5d which is the
current master HEAD of this repo (committed by tagomoris 3 weeks ago).

I will merge this pr with some adjustment, so that it sits nicely on top of c16ce5d.

**Comment by zonito** [comment]
Thanks, @fujimotos, appreciated!

**Comment by fujimotos** [comment]
Merged via e5d6aa13b74ca74e01d37caa7230cfc2bc204b1f.

**Comment by akerouanton** [comment]
@fujimotos @zonito Although this PR allows using self-signed TLS certs, it doesn't offer proper way of securely doing TLS because there's no way to specify which CA cert is accepted. With this change, if an attacker can mitm/redirect fluentd's network stream, they could still generate their own self-signed cert and bypass TLS promises. IMHO it could give a false sense of security. It would be great to be able to specify which CA certs are accepted (on top of what's in system truststore).

**Comment by fujimotos** [comment]
@akerouanton I created a ticket #112 to track that issue. I agree with you that it's better
if we provide cert options such as `TLSCertPath`.

> With this change, if an attacker can mitm/redirect fluentd's network stream, they could still generate their own self-signed cert and bypass TLS promises

The current option is register the certificate (which you want to use) into your operating system. I believe this works, since Go's TLS library recognizes system certificates by default.

**Pull request closed without merging**
