### PR TITLE
Do not allow writing events after fluent.Close()

### PR DESCRIPTION
**Pull request by fujimotos**
This implements proposal #104 by Albin Kerouanton.

The behavior of `Fluent.PostWithTime()` is a bit odd in sync mode;
It will silently reopen connections, even if the client has been
finalized via `Fluent.Close()`.

Change the behavior so that `PostWithTime()` returns an error
instead of doing an implicit reconnection in such a case.

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>

### CODE REVIEW

**Comment by fujimotos** [comment]
I spent some time this weekend trying to implement #104:

 * `Fluent` now rejects any event submission after Close().
 * `chanClosed` is renamed to `close` for brevity.

Also I added a unit test based on the sample code in the original proposal.
I slightly modified the code so that we can make use of `assert.Equal`.

@akerouanton Can you check out this PR and see if it is implemented as expected?
If anything feels wrong, please leave feedback here.

**Review by akerouanton — APPROVED** [review]

**Comment by fujimotos** [comment]
TODO: Merge this patch along with #107.

**Comment by akerouanton** [comment]
@fujimotos @tagomoris Let me know when this PR and #107 are merged and a new tag is released. I opened a PR to revendor v1.7.0 into docker. It's still opened, as there're some ongoing discussions that needs to be resolved first, but in any case, I'm willing to do the needed work to revendor when needed. If you're ok with that, just ping me when needed :wink:

**Comment by fujimotos** [comment]
@akerouanton FYI, v1.8.0 was out yesterday.

**Comment by akerouanton** [comment]
I'll update my PR on docker today :wink:

**Pull request merged**
